# mysql2 version 3.x
#   gem install mysql2
#
#   Ensure the mysql2 gem is defined in your Gemfile
#   gem 'mysql2'
#

default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password: bric_123
  timeout: 5000


development: &development
  <<: *default
  database: rss_reader_develpoment

test: &test
  <<: *default
  database: rss_reader_test

cucumber:
  <<: *test

production:
  <<: *development